# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: Build & test
on:
  push:
    branches: [ "main", "Development" ]
  pull_request:
    branches: [ "main", "Development" ]
  workflow_dispatch:
jobs:
  build_and_test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macOS-latest, ubuntu-latest, windows-latest ]
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          3.1.x
          5.0.x
          6.0.x
          7.0.x
          8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test - netcoreapp3.1
      run: dotnet test --configuration Release --filter "FullyQualifiedName~PowerShell6Tests" --framework netcoreapp3.1 --no-build --verbosity normal
    - name: Test - net5.0
      run: dotnet test --configuration Release --filter "FullyQualifiedName~PowerShell6Tests|FullyQualifiedName~PowerShell7Tests" --framework net5.0 --no-build --verbosity normal
    - name: Test - net6.0
      run: dotnet test --configuration Release --filter "FullyQualifiedName~PowerShell6Tests|FullyQualifiedName~PowerShell7Tests" --framework net6.0 --no-build --verbosity normal
    - name: Test - net7.0
      run: dotnet test --configuration Release --filter "FullyQualifiedName~PowerShell6Tests|FullyQualifiedName~PowerShell7Tests" --framework net7.0 --no-build --verbosity normal
    - name: Test - net8.0
      run: dotnet test --configuration Release --filter "FullyQualifiedName~PowerShell7Tests" --framework net8.0 --no-build --verbosity normal